defaults:
  - AllegroHandHora
env:
  reset_height_threshold: 0.2
  grasp_cache_name: 'public_allegro'

  reward:
    fingertipRewardScale: 2.0
    contactRewardScale: 1.0
    liftRewardScale: 2.0

  asset:
     handAsset: 'assets/allegro/allegro.urdf'
